version: "3.8"
services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"    # cổng cho các service của LocalStack (s3)
      - "4571:4571"
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=us-east-1
      - DATA_DIR=/tmp/new_localstack
    volumes:
      - "./localstack:/tmp/new_localstack"
